-- 003_turn_attempts.sql
-- Turn attempts (docs/decisions.md D28). Vapi fires several model requests per caller turn:
-- speculative ones on PARTIAL transcripts that it cancels when the caller keeps talking, then one
-- with the full transcript. Each request that runs the agent is an ATTEMPT. A turn is keyed on
-- (conversation_id, turn_index, transcript_hash):
--   - same transcript as a stored turn that SPOKE something -> replay it (genuine retry);
--   - different transcript -> the new attempt REPLACES any active attempt for that turn.
-- Every attempt records its own cost/tokens/latency, so conversation totals stay truthful:
--   totals = SUM(conversation_turns) + SUM(turn_attempts WHERE status <> 'completed')
-- (a completed attempt's usage is already in its turn row, so nothing is counted twice).
-- Supersession guard: write tools must hold an ACTIVE attempt (require_active_attempt) inside
-- the same transaction as their write, because abort is not immediate (D28).

begin;

create table turn_attempts (
  attempt_id            text primary key check (attempt_id <> ''),  -- generated by the backend before spawn
  conversation_id       text not null references conversations (conversation_id),
  turn_index            integer not null check (turn_index >= 0),
  transcript_hash       text not null,
  user_transcript       text,
  status                text not null default 'active'
    check (status in ('active', 'completed', 'replaced', 'aborted', 'failed')),
  status_reason         text,
  replaced_by           text references turn_attempts (attempt_id) deferrable initially deferred,
  started_at            timestamptz not null default now(),
  ended_at              timestamptz,
  -- latency
  ms_retrieval          integer,
  ms_first_token        integer,
  ms_total              integer,
  -- usage
  model                 text,
  input_tokens          integer,
  output_tokens         integer,
  cache_read_tokens     integer,
  cache_creation_tokens integer,
  cost_usd_estimate     numeric(12,6),
  sdk_duration_ms       integer,
  sdk_num_turns         integer,
  -- an attempt has ended exactly when it is no longer active
  check ((status = 'active') = (ended_at is null))
);

comment on column turn_attempts.cost_usd_estimate is
  'Agent SDK total_cost_usd for this attempt. Client-side ESTIMATE, not billing.';

-- At most one active attempt per turn: a new attempt must replace the old one first.
create unique index turn_attempts_one_active_per_turn
  on turn_attempts (conversation_id, turn_index) where status = 'active';
create index turn_attempts_conversation_turn_idx on turn_attempts (conversation_id, turn_index);

alter table conversation_turns
  add column attempt_id      text references turn_attempts (attempt_id),
  add column transcript_hash text;
alter table retrieval_logs add column attempt_id text references turn_attempts (attempt_id);
alter table tool_calls     add column attempt_id text references turn_attempts (attempt_id);

create index retrieval_logs_attempt_id_idx on retrieval_logs (attempt_id);
create index tool_calls_attempt_id_idx on tool_calls (attempt_id);

alter table turn_attempts enable row level security;

comment on column conversations.total_cost_usd is
  'SUM(conversation_turns.cost_usd_estimate) + SUM(turn_attempts.cost_usd_estimate WHERE status <> ''completed''). '
  'Client-side ESTIMATE, not billing. Set only by recompute_conversation_totals(), never incremented.';
comment on column conversations.total_input_tokens is
  'SUM over conversation_turns + non-completed turn_attempts. Set only by recompute_conversation_totals().';
comment on column conversations.total_output_tokens is
  'SUM over conversation_turns + non-completed turn_attempts. Set only by recompute_conversation_totals().';

-- ---------------------------------------------------------------------------
-- recompute_conversation_totals: the only writer of the conversation totals.
-- ---------------------------------------------------------------------------
create function recompute_conversation_totals(p_conversation_id text)
returns void
language sql
security invoker
set search_path = public
as $$
  update conversations c
     set total_cost_usd      = coalesce(t.cost, 0) + coalesce(a.cost, 0),
         total_input_tokens  = coalesce(t.input, 0) + coalesce(a.input, 0),
         total_output_tokens = coalesce(t.output, 0) + coalesce(a.output, 0)
    from (select sum(cost_usd_estimate) as cost, sum(input_tokens) as input, sum(output_tokens) as output
            from conversation_turns where conversation_id = p_conversation_id) t,
         (select sum(cost_usd_estimate) as cost, sum(input_tokens) as input, sum(output_tokens) as output
            from turn_attempts where conversation_id = p_conversation_id and status <> 'completed') a
   where c.conversation_id = p_conversation_id;
$$;

-- ---------------------------------------------------------------------------
-- begin_turn_attempt: one round trip at the start of every request that may run the agent.
--   1. upsert the conversation;
--   2. replay if the stored turn SPOKE something and has the same transcript hash;
--   3. otherwise mark as 'replaced' (replaced_by = the new attempt) every attempt for this turn
--      that is still 'active', or that was 'aborted' (client disconnected) with a DIFFERENT
--      transcript: in Vapi's flow the cancelled speculative request is replaced by the fuller
--      one. An aborted attempt followed by an IDENTICAL request stays 'aborted'.
--      Then insert the new attempt.
-- ---------------------------------------------------------------------------
create function begin_turn_attempt(
  p_conversation_id text,
  p_channel         text,
  p_caller          text,
  p_turn_index      integer,
  p_attempt_id      text,
  p_transcript_hash text,
  p_user_transcript text
)
returns table (action text, assistant_response text, answer_type text, replaced_attempt_ids text[])
language plpgsql
security invoker
set search_path = public
as $$
#variable_conflict use_column
declare
  v_response text;
  v_type     text;
  v_hash     text;
  v_replaced text[];
begin
  insert into conversations (conversation_id, channel, caller)
  values (p_conversation_id, p_channel, p_caller)
  on conflict (conversation_id) do nothing;

  select t.assistant_response, t.answer_type, t.transcript_hash
    into v_response, v_type, v_hash
    from conversation_turns t
   where t.conversation_id = p_conversation_id and t.turn_index = p_turn_index;
  if found and v_response is not null and v_hash = p_transcript_hash then
    return query select 'replay'::text, v_response, v_type, '{}'::text[];
    return;
  end if;

  with r as (
    update turn_attempts a
       set status = 'replaced',
           status_reason = case when a.status = 'aborted'
                                then 'aborted by the client, then replaced by a request with a different transcript'
                                else 'replaced by a newer request for the same turn' end,
           replaced_by = p_attempt_id,
           ended_at = coalesce(a.ended_at, now())
     where a.conversation_id = p_conversation_id
       and a.turn_index = p_turn_index
       and (a.status = 'active' or (a.status = 'aborted' and a.transcript_hash <> p_transcript_hash))
    returning a.attempt_id
  )
  select coalesce(array_agg(r.attempt_id), '{}') into v_replaced from r;

  insert into turn_attempts (attempt_id, conversation_id, turn_index, transcript_hash, user_transcript)
  values (p_attempt_id, p_conversation_id, p_turn_index, p_transcript_hash, p_user_transcript);

  return query select 'run'::text, null::text, null::text, v_replaced;
end;
$$;

-- ---------------------------------------------------------------------------
-- finish_turn_attempt: records an attempt's outcome and usage; returns its FINAL status.
--   - A status already set by someone else (e.g. 'replaced') is never overwritten.
--   - Only a 'completed' attempt writes the turn row (p_turn, a conversation_turns-shaped
--     jsonb). If the turn was already answered by another attempt, that attempt becomes
--     'replaced' so its usage still counts, and this attempt's answer is stored as the turn.
--   - Always recomputes the conversation totals.
-- ---------------------------------------------------------------------------
create function finish_turn_attempt(
  p_attempt_id    text,
  p_status        text,
  p_status_reason text,
  p_metrics       jsonb,
  p_turn          jsonb
)
returns text
language plpgsql
security invoker
set search_path = public
as $$
#variable_conflict use_column
declare
  v_status text;
  v_conv   text;
  v_idx    integer;
  v_prev   text;
begin
  if p_status not in ('completed', 'aborted', 'failed') then
    raise exception 'finish_turn_attempt: invalid status %', p_status;
  end if;

  update turn_attempts a
     set status                = case when a.status = 'active' then p_status else a.status end,
         status_reason         = case when a.status = 'active' then p_status_reason else a.status_reason end,
         ended_at              = coalesce(a.ended_at, now()),
         ms_retrieval          = (p_metrics ->> 'ms_retrieval')::integer,
         ms_first_token        = (p_metrics ->> 'ms_first_token')::integer,
         ms_total              = (p_metrics ->> 'ms_total')::integer,
         model                 = p_metrics ->> 'model',
         input_tokens          = (p_metrics ->> 'input_tokens')::integer,
         output_tokens         = (p_metrics ->> 'output_tokens')::integer,
         cache_read_tokens     = (p_metrics ->> 'cache_read_tokens')::integer,
         cache_creation_tokens = (p_metrics ->> 'cache_creation_tokens')::integer,
         cost_usd_estimate     = (p_metrics ->> 'cost_usd_estimate')::numeric,
         sdk_duration_ms       = (p_metrics ->> 'sdk_duration_ms')::integer,
         sdk_num_turns         = (p_metrics ->> 'sdk_num_turns')::integer
   where a.attempt_id = p_attempt_id
  returning a.status, a.conversation_id, a.turn_index into v_status, v_conv, v_idx;
  if not found then
    raise exception 'finish_turn_attempt: unknown attempt %', p_attempt_id;
  end if;

  if v_status = 'completed' and p_turn is not null then
    select t.attempt_id into v_prev
      from conversation_turns t
     where t.conversation_id = v_conv and t.turn_index = v_idx;
    if v_prev is not null and v_prev <> p_attempt_id then
      update turn_attempts
         set status = 'replaced',
             status_reason = 'turn answered again by a newer attempt',
             replaced_by = p_attempt_id
       where attempt_id = v_prev and status = 'completed';
    end if;

    insert into conversation_turns as t
      (conversation_id, turn_index, attempt_id, transcript_hash, user_transcript, assistant_response,
       answer_type, confidence_note, kb_chunk_ids, t_received, ms_retrieval, ms_first_token, ms_tools,
       ms_total, model, input_tokens, output_tokens, cache_read_tokens, cache_creation_tokens,
       cost_usd_estimate, sdk_duration_ms, sdk_num_turns)
    select v_conv, v_idx, p_attempt_id, r.transcript_hash, r.user_transcript, r.assistant_response,
           r.answer_type, r.confidence_note, coalesce(r.kb_chunk_ids, '{}'), coalesce(r.t_received, now()),
           r.ms_retrieval, r.ms_first_token, r.ms_tools, r.ms_total, r.model, r.input_tokens,
           r.output_tokens, r.cache_read_tokens, r.cache_creation_tokens, r.cost_usd_estimate,
           r.sdk_duration_ms, r.sdk_num_turns
      from jsonb_populate_record(null::conversation_turns, p_turn) r
    on conflict (conversation_id, turn_index) do update
       set attempt_id = excluded.attempt_id,
           transcript_hash = excluded.transcript_hash,
           user_transcript = excluded.user_transcript,
           assistant_response = excluded.assistant_response,
           answer_type = excluded.answer_type,
           confidence_note = excluded.confidence_note,
           kb_chunk_ids = excluded.kb_chunk_ids,
           t_received = excluded.t_received,
           ms_retrieval = excluded.ms_retrieval,
           ms_first_token = excluded.ms_first_token,
           ms_tools = excluded.ms_tools,
           ms_total = excluded.ms_total,
           model = excluded.model,
           input_tokens = excluded.input_tokens,
           output_tokens = excluded.output_tokens,
           cache_read_tokens = excluded.cache_read_tokens,
           cache_creation_tokens = excluded.cache_creation_tokens,
           cost_usd_estimate = excluded.cost_usd_estimate,
           sdk_duration_ms = excluded.sdk_duration_ms,
           sdk_num_turns = excluded.sdk_num_turns;
  end if;

  perform recompute_conversation_totals(v_conv);
  return v_status;
end;
$$;

-- ---------------------------------------------------------------------------
-- Supersession guard for write tools.
--   attempt_is_active: a plain check (used by the MCP write path before calling a write).
--   require_active_attempt: call INSIDE a write RPC's transaction. The FOR SHARE lock makes a
--   concurrent "mark replaced" wait until the write commits, so a write and a replacement can
--   never interleave. Raises P0001 'ATTEMPT_NOT_ACTIVE: ...' if the attempt is not active.
-- ---------------------------------------------------------------------------
create function attempt_is_active(p_attempt_id text)
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select coalesce((select status = 'active' from turn_attempts where attempt_id = p_attempt_id), false);
$$;

create function require_active_attempt(p_attempt_id text)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  perform 1 from turn_attempts where attempt_id = p_attempt_id and status = 'active' for share;
  if not found then
    raise exception 'ATTEMPT_NOT_ACTIVE: attempt % is not active', p_attempt_id using errcode = 'P0001';
  end if;
end;
$$;

revoke execute on function recompute_conversation_totals(text) from public, anon, authenticated;
revoke execute on function begin_turn_attempt(text, text, text, integer, text, text, text) from public, anon, authenticated;
revoke execute on function finish_turn_attempt(text, text, text, jsonb, jsonb) from public, anon, authenticated;
revoke execute on function attempt_is_active(text) from public, anon, authenticated;
revoke execute on function require_active_attempt(text) from public, anon, authenticated;
grant execute on function recompute_conversation_totals(text) to service_role;
grant execute on function begin_turn_attempt(text, text, text, integer, text, text, text) to service_role;
grant execute on function finish_turn_attempt(text, text, text, jsonb, jsonb) to service_role;
grant execute on function attempt_is_active(text) to service_role;
grant execute on function require_active_attempt(text) to service_role;

commit;
